-- Migration 002: store_objects table.
-- This table has been moved to the separate store database (internal/store).
-- The store package now owns its own schema via store.EnsureSchema().
-- This file is kept as a no-op to preserve migration version numbering.
